server:
  port: 8086
#spring:
#  application:
#   name: taskservice
#  profiles:
#    active: default
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?createDatabaseIfNotExist=true
    username: root
    password: welcome
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: task