server:
  port: 8191
   
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tejpratapkus/spring-boot-config-store
          search-paths:
          - '*service'
          #username: root --for private
          #password: test123
         