spring:
  application:
    name: discoveryservice  profiles:    active: default
    
eureka:  client:    register-with-eureka: false
    fetch-registry: false
  datacenter: India
  environment: production
server:
  port: 8761  