spring:
  application:
    name: clientservice # profiles: #   active: default     
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token  
server:
  servlet:
    session:
      cookie:
        name: KSESSION     
  port: 8085
    